version: '3.8'

services:
  backend:
    build:
      context: ./api
    ports:
      - "8800:8800"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123
      - DB_NAME=bdlivraria
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: bdlivraria
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./api/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
